config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Home page should be pages#home
  root to: 'pages#home'

  # Root to profile page
  get 'pages/profile' => 'pages#profile', as: 'profile'

  # As a user, I want to see all available teachers, see indivudal profiles and create a new teacher profile for me
  # As a teacher, I want to edit my teacher profile
  resources 'bookings', only:[:new, :create, :index, :show, :destroy]
  patch 'bookings/:id/approve', to: 'bookings#approve', as: :approve_booking
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :cancel
  post 'bookings/:id/complete', to: 'bookings#complete', as: :complete


  resources 'teachers', only:[:index, :show, :edit, :update, :new, :create, :destroy] do
     resources 'bookings', only:[:new, :create, :destroy]

    # As a user, I want to see all my bookings create a new booking and delete it if I no longer want the session
    # As a teacher, I want to see all my bookings, edit their status and delete them
    # As a teacher, I want to show all my skills, add new skills and delete skills I no longer possess
    resources 'teacher_skills', only:[:index, :new, :create, :destroy]
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :teacher
  belongs_to :user
  after_initialize :init

  validates :status, presence: true

  def init
    self.status ||= "Pending"
  end

  def completed!
    update_attribute :status, "complete"
  end

  def approved!
    update_attribute :status, "approved"
  end

  def cancelled!
    update_attribute :status, "cancelled"
  end
end



# removed option from user or teacher depending on who cancels

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user_bookings = current_user.bookings
    # rather than If statement
    @teacher_bookings = current_user.teacher.try(:bookings)
    @teacher = params[:teacher_id]
    @teacher_booking = policy_scope(Teacher)
  end

  def show
    set_booking
    @teacher = params[:teacher_id]
    authorize @booking
  end

  # def edit
  #   @booking = Booking.find(params[:id])
  # end

  # def update
  #   booking = Booking.find(params[:id])
  #   booking.update(booking_params)
  #   redirect_to booking_path(booking)
  # end

  def new
   @teacher = Teacher.find(params[:teacher_id])
   @booking = Booking.new
   authorize @booking
  end


 def approve
  set_booking
  authorize @booking
  @booking.approved!
  redirect_to bookings_path
end

def cancel
  set_booking
  authorize @booking
  @booking.cancelled!
  redirect_to bookings_path
end

def complete
  set_booking
  authorize @booking
  @booking.completed!
  redirect_to bookings_path
end


def create
  @user = current_user
  @teacher = Teacher.find(params[:teacher_id])
  @booking = Booking.new(booking_params)
  @booking.user = current_user
  @booking.teacher_id = @teacher.id
  if @booking.save
    authorize @booking
    redirect_to booking_path(@booking)
  else
    render :new
  end
end

def destroy
  set_booking
  authorize @booking
  @booking.destroy
  redirect_to bookings_path
end

private

def set_booking
  @booking = Booking.find(params[:id])
end

def booking_params
  params.require(:booking).permit(:teacher_id, :start_time, :end_time, :total_price, :status)
end

def booking_time_params
  params.require(:booking).permit(:start_time, :end_time)
end

end
#controller, routes, added routing buttons to teacher for new booking, teacher index/user index of bookings

app/views/bookings/_form.html.erb
<div class="container" style="text-align: center">
  <h1>New Booking</h1>

  <%= simple_form_for([@teacher, @booking]) do |f| %>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= f.input :start_time %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= f.input :end_time %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= f.button :submit, class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<h1>this is an edit page</h1>

  <div class="container">
  <div class="row">
    <div class="col-xs-12">

        <%= render 'form', booking: @booking%>

      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<!-- Display all the users bookings -->
<h1>Teachers</h1>

<% @user_bookings.each do |booking| %>
<div class="product">

  <img src="https://avatars2.githubusercontent.com/u/22443485?s=460&v=4" alt="kudoz" class="avatar-large product-image">

  <div class='product-body'>
    <h3>Teacher:</h3>
    <p><%= booking.teacher.full_name %></p>
  </div>

  <div class='product-body'>
    <%  if booking.start_time.present? %>
    <h3>Date:</h3>
    <p><%= booking.start_time.strftime("%d-%b-%Y") %></p>
    <% end %>
  </div>

  <div class='product-body'>
    <%  if booking.start_time.present? %>
    <h3>Start time:</h3>
    <p><%= booking.start_time.strftime("%H:%M") %></p>
    <% end %>
  </div>

  <div class='product-body'>
    <%  if booking.end_time.present? %>
    <h3>End time:</h3>
    <p><%= booking.end_time.strftime("%H:%M") %></p>
    <% end %>
  </div>

  <div class='product-body'>
    <h3>Status:</h3>
    <p><%= booking.status %></p>
    <% if booking.status == "complete" %>
      <p>total price: $<%= ((booking.end_time - booking.start_time) / 3600) * booking.teacher.hourly_price %></p>
      <% end %>
      <%= link_to 'Cancel', cancel_path(booking), method: :patch unless booking.status == "cancelled" || booking.status == "complete" %>
      <% if booking.status == "cancelled" || booking.status == "complete" %>
      <!-- Lets leave that out for now -->
      <%#= link_to "Remove", booking_path(booking.id), method: :delete %>
      <br>
      <br>
      <br>
    <% end %>
  </div>

  <div class="product-body">

    <%= link_to 'Cancel', cancel_path(booking), method: :patch unless booking.status == "cancelled" || booking.status == "complete" %>
    <% if booking.status == "cancelled" || booking.status == "complete" %>
    <%= link_to "Remove", booking_path(booking.id), method: :delete %>
    <% end %>
  </div>
</div>
<% end %>




<% if @teacher_bookings %>
<h1>Clients</h1>

<% @teacher_bookings.each do |booking|%>
  <div class="product">
    <img src="https://avatars2.githubusercontent.com/u/22443485?s=460&v=4" alt="kudoz" class="avatar-large product-image">
    <div class='product-body'>
      <h3>Student:</h3>
      <p><%= booking.user.first_name %></p>
    </div>
    <div class='product-body'>
      <%  if booking.start_time.present? %>
      <h3>Date:</h3>
      <p><%= booking.start_time.strftime("%d-%b-%Y") %></p>
      <% end %>
    </div>
    <div class='product-body'>
      <%  if booking.start_time.present? %>
      <h3>Start time:</h3>
      <p><%= booking.start_time.strftime("%H:%M") %></p>
      <% end %>
    </div>
    <div class='product-body'>
      <%  if booking.end_time.present? %>
      <h3>End time:</h3>
      <p><%= booking.end_time.strftime("%H:%M") %></p>
      <% end %>
    </div>
    <div class='product-body'>
      <h3>Status:</h3>
      <p><%= booking.status %></p>
    </div>
    <div class='product-body'>
      <div class='product-body'>
        <% if booking.status == "complete" %>
        <% if booking.end_time.present? && booking.start_time.present? %>
        <p>total price: $<%= ((booking.end_time - booking.start_time) / 3600) * booking.teacher.hourly_price %></p>
        <% end %>
        <% end %>
      </div>
      <div class='product-body'>
        <%= link_to 'Approve', approve_booking_path(booking), method: :patch unless booking.status == "cancelled" || booking.status == "complete" || booking.status == "approved" %>
      </div>
      <div class='product-body'>
        <%= link_to 'Cancel', cancel_path(booking), method: :patch unless booking.status == "cancelled" || booking.status == "complete" %>
      </div>
      <div class='product-body'>
        <%= link_to 'Mark Completed', complete_path(booking), method: :post unless booking.status == "cancelled" || booking.status == "complete" %>
        <% if booking.status == "cancelled" || booking.status == "complete" %>
        <%= link_to "Remove", booking_path(booking.id), method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/bookings/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
        <div class="col-xs-12">

            <%= render 'form', booking: @booking %>

        </div>

    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="product">



    <img src="https://avatars2.githubusercontent.com/u/22443485?s=460&v=4" alt="kudoz" class="avatar-large">

    <div class='product-body'>
      <h3>Teacher:</h3>
      <p><%= @booking.teacher.full_name %></p>
    </div>

    <div class='product-body'>
      <h3>Date:</h3>
      <p><%= @booking.end_time.strftime("%d-%b-%Y") %></p>
    </div>

    <div class='product-body'>
      <h3>Start time:</h3>
      <p><%= @booking.start_time.strftime("%H:%M") %></p>
    </div>

    <div class='product-body'>
      <h3>End time:</h3>
      <p><%= @booking.end_time.strftime("%H:%M") %></p>
    </div>

    <div class='product-body'>
      <h3>Status:</h3>
      <p><%= @booking.status %></p>
    </div>

        <div class='product-body'>
      <h3>Price:</h3>
      <p><%= ((@booking.end_time - @booking.start_time) / 3600) * @booking.teacher.hourly_price %></p>
    </div>
  </div>


<%= link_to "Back to My Bookings", bookings_path %>