config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Home page should be pages#home
  root to: 'pages#home'

  # Root to profile page
  get 'pages/profile' => 'pages#profile', as: 'profile'

  # As a user, I want to see all available teachers, see indivudal profiles and create a new teacher profile for me
  # As a teacher, I want to edit my teacher profile
  resources 'bookings', only:[:new, :create, :index, :show, :destroy]
  patch 'bookings/:id/approve', to: 'bookings#approve', as: :approve_booking
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :cancel
  post 'bookings/:id/complete', to: 'bookings#complete', as: :complete


  resources 'teachers', only:[:index, :show, :edit, :update, :new, :create, :destroy] do
     resources 'bookings', only:[:new, :create, :destroy]

    # As a user, I want to see all my bookings create a new booking and delete it if I no longer want the session
    # As a teacher, I want to see all my bookings, edit their status and delete them
    # As a teacher, I want to show all my skills, add new skills and delete skills I no longer possess
    resources 'teacher_skills', only:[:index, :new, :create, :destroy]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Start of the Navbar -->

<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
  <%= image_tag "logo.png", alt: "Off the wagon logo" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs ">
  <!-- Displayed when user is  logged in -->
    <% if user_signed_in? %>

      <!-- If User is not a teacher, show "Become a teacher" -->
      <%# if policy(Teacher).create? %>
      <%= link_to "Become a teacher", new_teacher_path, class: "navbar-wagon-item navbar-wagon-link" if current_user.teacher.nil? %>
      <%# end %>

      <!-- Check Bookings -->
      <% if current_user %>
      <%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>

      <a class="navbar-wagon-item navbar-wagon-link" href=" <%= teachers_path %>">All teachers</a>

      <!-- Avatar with the remainding Links as dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.teacher.try(:photo).present? %>
          <%= cl_image_tag current_user.teacher.photo, height: 300, width: 400, class: 'avatar-navbar dropdown-toggle', id: 'navbar-wagon-menu', data: { toggle: 'dropdown' } %>
          <% else %>
          <%= image_tag 'https://res.cloudinary.com/dftybtoej/image/upload/v1542030994/empty_profile.jpg', class: 'avatar-navbar dropdown-toggle', id: 'navbar-wagon-menu', data: { toggle: 'dropdown' } %>
          <% end %>


          <!--<1img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar-navbar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">-->
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <!-- Show user Profile -->
            <!-- We don't have a route to simply display a users profile -->
            <li>
              <%= link_to "Edit User Profile", edit_user_registration_path %>
            </li>

            <!-- Show Teacher profile if it exists -->
            <% if current_user.teacher %>
              <li>

                <%= link_to "Teacher Profile", teacher_path(current_user.teacher), class: "navbar-wagon-item navbar-wagon-link" %>
              </li>
            <% end %>

            <!-- Sign Out -->
            <li>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete,  class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

          </ul>
        </div>
      </div>


  <!-- Displayed when user is NOT logged in -->
    <% else %>
      <!--     <a href="#" class="navbar-wagon-item navbar-wagon-link">Sign up</a> -->
      <%= link_to "Sign up",  new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!--     <a href="#" class="navbar-wagon-item navbar-wagon-link">Sign in</a> -->
      <%= link_to "Sign in", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>


  <!-- Dropdown appearing on mobile only -->

  <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <!-- If User is signed in -->
        <% if user_signed_in? %>

          <!-- If User is not a teacher, show "Become a teacher" -->
          <li>
            <%= link_to "Become a teacher", new_teacher_path, class: "navbar-wagon-item navbar-wagon-link" if current_user.teacher.nil? %>
          </li>

          <!-- Check Bookings -->
          <li>
            <%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>

          <!-- Edit User / Student Profile -->
          <!-- We don't have a route to simply display a users profile -->
          <li>
            <%= link_to "Edit User Profile", edit_user_registration_path %>
          </li>

          <!-- Show Teacher profile if it exists -->
          <% if current_user.teacher %>
            <li>
              <%= link_to "Teacher Profile", teacher_path(current_user.teacher), class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
          <% end %>

          <!-- Sign Out -->
          <li>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete,  class: "navbar-wagon-item navbar-wagon-link" %>
          </li>


        <!-- If User is NOT signed in -->
        <% else %>
          <!-- Sign UP -->
          <li>
            <%= link_to "Sign up",  new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>

          <!-- Sign IN -->
          <li>
            <%= link_to "Sign in", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>


        <% end %>

      </ul>
    </div>
  </div>

</div>


    <!-- Profile picture with dropdown list -->
<!--     <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div> -->