config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Home page should be pages#home
  root to: 'pages#home'

  # Root to profile page
  get 'pages/profile' => 'pages#profile', as: 'profile'

  # As a user, I want to see all available teachers, see indivudal profiles and create a new teacher profile for me
  # As a teacher, I want to edit my teacher profile
  resources 'bookings', only:[:new, :create, :index, :show, :destroy]
  patch 'bookings/:id/approve', to: 'bookings#approve', as: :approve_booking
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :cancel
  post 'bookings/:id/complete', to: 'bookings#complete', as: :complete


  resources 'teachers', only:[:index, :show, :edit, :update, :new, :create, :destroy] do
     resources 'bookings', only:[:new, :create, :destroy]

    # As a user, I want to see all my bookings create a new booking and delete it if I no longer want the session
    # As a teacher, I want to see all my bookings, edit their status and delete them
    # As a teacher, I want to show all my skills, add new skills and delete skills I no longer possess
    resources 'teacher_skills', only:[:index, :new, :create, :destroy]
  end

end

app/models/teacher_skill.rb
class TeacherSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :teacher
  before_save :set_name
  validates :level, inclusion: [1, 2, 3, 4, 5]
  validates_uniqueness_of :teacher_id, :scope => [:skill_id]


  def set_name
    self.name = self.skill.name
  end

end

app/controllers/teacher_skills_controller.rb
# I think we only need delete, new and create

class TeacherSkillsController < ApplicationController
  before_action :set_teacher_skill, only: [:show, :edit, :update]
  # def index
  #   @teacher_skills = TeacherSkill.all
  # end

  # def show
  # end

  # def edit
  # end

  # def update
  #   @teacher = Teacher.find(params[:teacher_id])
  #   if @teacher_skill.update(teacher_skill_params)
  #     redirect_to teacher_path(@teacher)
  #   else
  #     render :new
  #   end
  # end

  def new
    @new_skill = TeacherSkill.new
    @teacher = Teacher.find(params[:teacher_id])
  end

  def create
    @teacher_skill = TeacherSkill.new(teacher_skill_params)
    @teacher = Teacher.find(params[:teacher_id])
    authorize @teacher
    @teacher_skill.teacher = @teacher

    if @teacher_skill.save
      redirect_to teacher_path(@teacher), notice: 'Skill succesfully created'
    else
      @teacher_skills = TeacherSkill.where(teacher_id: @teacher.id)
      @new_skill = @teacher_skill
      puts "Skill could not be created"
      render "teachers/show" ### render teacher's new
    end
  end



  def destroy
    @teacher = Teacher.find(params[:teacher_id])
    # dont know why, but it is the way it is
    @teacher_skill = TeacherSkill.find(params[:id])
    authorize @teacher_skill
    @teacher_skill.destroy
    redirect_to teacher_path(@teacher)
  end

  private

  def set_teacher_skill
    @teacher_skill = TeacherSkill.find(params[:id])
  end

  def teacher_skill_params
    params.require(:teacher_skill).permit(:level, :skill_id, :teacher_id, :teacher_skill_id)
  end

end

app/views/teacher_skills/_form.html.erb
<div class="wrapper">
  <div class="container">
<%= simple_form_for [@teacher, @new_skill] do |f| %>
<div class="row">
          <div class="col-xs-6 col-xs-offset-3">
  <%= f.association :skill, as: :select %>
</div>
</div>
<div class="row">
          <div class="col-xs-6 col-xs-offset-3">
  <%= f.input :level, label: 'Level (1-5)' %>
</div>
</div>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>
</div>
</div>

app/views/teacher_skills/create.html.erb
<h1>TeacherSkills#create</h1>
<p>Find me in app/views/teacher_skills/create.html.erb</p>

app/views/teacher_skills/edit.html.erb
<h1>TeacherSkills#edit</h1>
<p>Find me in app/views/teacher_skills/edit.html.erb</p>

app/views/teacher_skills/index.html.erb
<h1>TeacherSkills#index</h1>
<p>Find me in app/views/teacher_skills/index.html.erb</p>

app/views/teacher_skills/new.html.erb
<h1>Create a new skill</h1>


<%= simple_form_for [@teacher, @new_skill], :url => teacher_teacher_skills_path, :method => :post do |f| %>
  <%= f.association :skill, as: :radio_buttons %>
  <%= f.input :level %>
  <%= f.submit %>
<% end %>

app/views/teacher_skills/show.html.erb
<h1>TeacherSkills#show</h1>
<p>Find me in app/views/teacher_skills/show.html.erb</p>

app/views/teacher_skills/update.html.erb
<h1>TeacherSkills#update</h1>
<p>Find me in app/views/teacher_skills/update.html.erb</p>