config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Home page should be pages#home
  root to: 'pages#home'

  # Root to profile page
  get 'pages/profile' => 'pages#profile', as: 'profile'

  # As a user, I want to see all available teachers, see indivudal profiles and create a new teacher profile for me
  # As a teacher, I want to edit my teacher profile
  resources 'bookings', only:[:new, :create, :index, :show, :destroy]
  patch 'bookings/:id/approve', to: 'bookings#approve', as: :approve_booking
  patch 'bookings/:id/cancel', to: 'bookings#cancel', as: :cancel
  post 'bookings/:id/complete', to: 'bookings#complete', as: :complete


  resources 'teachers', only:[:index, :show, :edit, :update, :new, :create, :destroy] do
     resources 'bookings', only:[:new, :create, :destroy]

    # As a user, I want to see all my bookings create a new booking and delete it if I no longer want the session
    # As a teacher, I want to see all my bookings, edit their status and delete them
    # As a teacher, I want to show all my skills, add new skills and delete skills I no longer possess
    resources 'teacher_skills', only:[:index, :new, :create, :destroy]
  end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  before_save :full_name
  belongs_to :user
  has_many :teacher_skills, dependent: :destroy
  has_many :skills, through: :teacher_skills
  has_many :bookings, dependent: :destroy
  validates :user_id, uniqueness: true

  mount_uploader :photo, PhotoUploader

  # Pg Search Start
  # Search by Teacher.user name and skill category
  include PgSearch
  pg_search_scope :pg_search,
    against: [ :full_name],
    associated_against: {
      teacher_skills: [:name]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  # Pg Search End


  def top_skill
    self.teacher_skills.order(level: :desc).first
  end

  def full_name
    self.full_name = "#{self.user.first_name} #{self.user.last_name}"
  end
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  before_action :set_teacher, only: [:show, :update, :edit]
  # def profile
  # end

  def new #done
    @teacher = Teacher.new
  end

  def create
    teacher = Teacher.new(teacher_params)
    teacher.save
    redirect_to teacher_path(teacher)
  end

  def index
    @teacher = Teacher.all
  end

  def show
    # set_teacher
  end


  def edit #done
    #set_teacher
  end

  def update
    # set_teacher
  end
end

private

def set_teacher
  @teacher = Teacher.find(params[:id])
end

def teacher_params
  # If any errors are encountered, it might be due to ':id' below
  params.require(:teacher).permit(:id, :average_rating, :hourly_price, :available_from, :availble_to)
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :update, :edit, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # works
  def new
    @teacher = Teacher.new
    authorize @teacher
  end

  # works
  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.user = current_user
    authorize @teacher
    if @teacher.save
      redirect_to teacher_path(@teacher), notice: 'Profile succesfully created'
    else
      puts "This teacher didn't save"
      render :new
    end
  end

  # works
  def index
    # Geo coding start
    if params[:location].present?
      @teachers = Teacher.near(params[:location], 60)
    else
      @teachers = Teacher.all
    end

    if params[:query].present?
      @teachers = @teachers.pg_search(params[:query])
    end

    @markers = @teachers.map do |teacher|
      {
        lng: teacher.longitude,
        lat: teacher.latitude,
        infoWindow: { content: render_to_string(partial: "/teachers/map_window", locals: { teacher: teacher }) }
      }
    end
    # Geo coding end
    @teacher_skills = TeacherSkill.all
    policy_scope(Teacher)
  end


  # works
  def show
    # set_teacher
    @teacher_skills = TeacherSkill.where(teacher_id: @teacher.id)
    @new_skill = TeacherSkill.new
    @skills = Skill.all
    authorize @teacher
  end

  # works
  def edit
    # set_teacher
    authorize @teacher
  end

  # works
  def update
    # set_teacher
    authorize @teacher
    if @teacher.update(teacher_params)
      redirect_to teacher_path(@teacher), notice: 'Profile successfully updated'
    else
      render :edit
    end
  end

  def destroy
    authorize @teacher
    @teacher.destroy
    redirect_to teachers_path
  end
end

private

def set_teacher
  @teacher = Teacher.find(params[:id])
end

def teacher_params
  # If any errors are encountered, it might be due to ':id' below
  params.require(:teacher).permit(:user_id, :average_rating, :hourly_price, :available_from, :available_to, :photo)
end

app/views/teachers/_card.html.erb
<% skills = TeacherSkill.where(teacher_id: teacher.id) %>
<% top_skill = skills.order('level DESC').first.try(:name) %>

<%= link_to teacher_path(teacher) do %>

  <div class="card <%#= top_skill %>">
    <div class="block-1">

      <div class="skills">
        <%= top_skill %>
      </div>

      <div class="image-wrapper">
        <div class="<%= top_skill %> "></div>
      </div>


      <% if teacher.user.photo != nil %>
      <%= image_tag teacher.user.photo, class: 'avatar' %>
      <% else %>
      <%= image_tag 'https://res.cloudinary.com/dftybtoej/image/upload/v1542030994/empty_profile.jpg', class: 'avatar' %>
      <% end %>

      <!-- <a class="card-link" href="<%= teacher_path(teacher) %>" ></a> -->
    </div>


    <div class="card-description">
      <div>
        <%= teacher.full_name %>
      </div>
    </div>
  </div>
<% end %>

app/views/teachers/_form.html.erb
<%= simple_form_for(@teacher) do |f| %>
<div class="row">
          <div class="col-xs-6 col-xs-offset-3">
  <%= f.input :hourly_price, label: 'Hourly price (USD)', placeholder: "25" %>
</div>
</div>
<div class="row">
          <div class="col-xs-6 col-xs-offset-3">
  <%= f.input :available_from %>
</div>
</div>
<div class="row">
          <div class="col-xs-6 col-xs-offset-3">
  <%= f.input :available_to %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, class: 'btn btn-primary' %>

</div>
</div>
<% end %>

app/views/teachers/_map_window.html.erb
<div class="mapboxgl-popup">
  <div class="mapboxgl-popup-content">
    <img class="avatar" src="https://avatars2.githubusercontent.com/u/22443485?s=460&v=4">
    <a class="card-link" href="<%= teacher_path(teacher) %>" ></a>
    <p> <%=  teacher.full_name  %></p>
    <p> <%= teacher.hourly_price %>€ per hour </p>
    <% teacher.teacher_skills.each do |skill| %>
    <ul>
      <p>Skills:</p>
      <li>
         <%= skill.name %>
      </li>
    </ul>
    <% end %>
  </div>
</div>

app/views/teachers/edit.html.erb
<div class="wrapper">
  <div class="container">
    <div class="form">

      <h2>Edit your details</h2>

      <%= render 'form', teacher: @teacher %>

    </div>
  </div>
</div>

app/views/teachers/index.html.erb
<div class="wrapper">
  <div class="title">
    <h1 class="text-center">Select the teacher you would like to book</h1>
  </div>
  <div class="flex-container">
    <!-- Container Start -->
    <!-- Beginning of Teacher Card -->

    <div class="container">
      <div class="teacher-container">

        <% if @teachers.length == 0 %>
          <h3>No teachers found, go back to home page by clicking <%= link_to "here", root_path %> </h3>
        <% else %>
        <h3>Select from <%= @teachers.length %> Teachers</h3>

        <div class="row">
          <% @teachers.each do |teacher| %>
          <div class="col-xs-12 col-sm-6">
            <%= render "teachers/card", teacher: teacher %>
          </div>
          <!-- col div -->

          <% end %>
        <!-- Each end -->

        </div>
        <!-- Row div -->

        <% end %>
        <!-- If end -->

    </div>
    <!-- teacher cointainer div -->
  </div>
  <!-- container -->

  <!-- End of Teacher Card -->
  <!-- Mapbox Maps -->
  <div
  id="map"
  style="height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  >
  </div>
  <!-- flex container -->
</div>
<!-- wrapper -->
</div>

app/views/teachers/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="form">

      <h1>Become a teacher</h1>

      <%= render 'form', teacher: @teacher %>

    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<div class="wrapper">

<div class="container text-center">
  <div class="profile_card">
    <h1><%= @teacher.full_name %></h1>
    <% if @teacher.user.photo != nil %>
    <%= image_tag @teacher.user.photo, class: "profile_photo" %>
    <% else %>
    <%= cl_image_tag @teacher.photo, height: 300, width: 400, crop: :fill %>
    <% end %>

  <h3>Skills:</h3>
   <% @teacher_skills.each do |skill| %>
    <h4 class="skill"><%= skill.name.capitalize %></h4>
    <% level = "" %>
    <% case skill.level %>
      <% when 1 then level="Fresher" %>
      <% when 2 then level="Intermediate" %>
      <% when 3 then level="Knight" %>
      <% when 4 then level="Baws" %>
      <% when 5 then level="God" %>
    <% else level="wtf?" %>
    <% end %>
    <p><%= level.capitalize %>
      <% if user_signed_in? %>
        <% if @teacher.user.id == current_user.id || current_user.admin %>
            <%= link_to "delete", teacher_teacher_skill_path(@teacher, skill), method: :delete  %>
        <% end %>
      <% end %>
    </p>

  <% end %>
  <% if user_signed_in? %>
    <% if @teacher.user.id == current_user.id || current_user.admin %>
      <%=  render 'teacher_skills/form' %>
    <% end %>
  <% end %>

<!-- Checks if user is signed in -->
<% if user_signed_in? %>
  <%= link_to "Destroy this biaaaatch", teacher_path(@teacher), method: :delete  if current_user.admin %>
  <!-- Validates that User cannot book himself -->
  <% if current_user.id == @teacher.user_id %>
      <p><%= link_to 'Edit teacher details', edit_teacher_path(@teacher) %></p>
  <% else %>
      <p><%= link_to 'Book this teacher!', new_teacher_booking_path(@teacher) %></p>
  <% end %>

<!-- Show Book this teacher if User is not logged in to redirect him to sign up -->
<% else %>
  <p><%= link_to 'Book this teacher!', new_user_session_path %></p>
<% end %>

<p><%= link_to 'Go Back to home page', root_path %> </p>
</div>
</div>